### ISSUE TITLE
"Cache-Control: public, max-age=0" is set by default

### ISSUE THREAD

**Issue by SVasilev** [pillarjs/send#110]
Hello,
I am using this module for a while and I encountered the following problem. I cannot remove the Cache-Control header. It is always set by default to some value. I noticed that this behaviour comes from:
```
if (!res.getHeader('Cache-Control')) {
  res.setHeader('Cache-Control', 'public, max-age=' + Math.floor(this._maxage / 1000));
}
```
I managed to make a work-around with the "on-headers" module, mentioned in issue https://github.com/expressjs/serve-static/issues/5 which looks like this:
```
var onHeaders = require('on-headers');
onHeaders(function() {
  this.removeHeader('Cache-Control');
}
```
But this approach looks pretty sketchy. So the question is  why can't this be configured somewhere in the options, because after researching Apache and Nginx I saw that they don't add the Cache-Control header by default and I want to accomplish that behaviour. Besides it looks like the right approach to me because after looking at the HTTP1.1 spec I found:
> Unless specifically constrained by a cache-control (section 14.9)
   directive, a caching system MAY always store a successful response
   (see section 13.8) as a cache entry, MAY return it without validation
   if it is fresh, and MAY return it after successful validation.

So, it seems that is up to the Content Delivery Networks (Akamai, etc) to decide whether something is cachable by default. So is there a reason for forcing the Cache-Control by default in this module?

**Comment by dougwilson** [comment]
> But this approach looks pretty sketchy. So the question is why can't this be configured somewhere in the options, because after researching Apache and Nginx I saw that they don't add the Cache-Control header by default and I want to accomplish that behavior.

Hi @SVasilev, sorry no one else has dropped by! The current way does work, yes. Not sure what is "sketchy" about it, though. But we can certainly add a better API to prevent this module from setting a `Cache-Control` header.

> So is there a reason for forcing the Cache-Control by default in this module?

The reason it is there by default is because the default behavior is extremely undefined. Your assest may or may not get cached by an intermediate, it may or may not get cached by the end user, and even then, who knows how long it will be cached for? Different CDNs, web browsers, etc. have different default rules, since there is no specification that outlines any default rules. By always providing a `Cache-Control` you take almost all the gues work out of it. Apache & nginx are more bare-bones than this module is out-of-the-box, so it makes sense that we provide more features out-of-the-box here.

I would hightly recommend you re-consider not sending a `Cache-Control`, because you'll no lnger have any idea what is caching your assets and for how long.

Regardless we can make a better API to turn off the header :)

**Comment by SVasilev** [comment]
Hi and thanks for replying. It is sketchy because the "on-headers" module relies on Node.js implementation which may change anytime. Would you be interested in a pull request to provide option to control the Cache-Control behavior?

**Comment by dougwilson** [comment]
> It is sketchy because the "on-headers" module relies on Node.js implementation which may change anytime.

Pretty much everything "relies on Node.js implementation which may change at anytime", so i.m.o that's not a good reason. Besides, that module is part of an organization of folks working to ensure that if something does break, it is quickly fixed, and all it really does is replace `res.writeHead`, which is a public API (https://nodejs.org/api/http.html#http_response_writehead_statuscode_statusmessage_headers) in a stable API.

This module, on the other-hand, relies to `on-finished`, which is one that truly uses un-documented APIs and is very likely to break on Node.js changes. If that is your concern, I would not use this module.

> Would you be interested in a pull request to provide option to control the Cache-Control behavior?

I would be, absolutely! I have been thinking about this, and would have actually made the change already, but cannot think of a good API that does not have options that exclude one another. For a higher chance of getting a PR accepted, you may want to discuss what you're thinking the API for `send` would be with your change first :)

**Comment by SVasilev** [comment]
Approach 1:
  If maxAge property has a value of -1, then Cache-Control header is not set.
  This does not look very intuitive but still a possible solution.
Approach 2:
  Add another property: "cacheControl" with type boolean. By default it is true.
  If set to true the Cache-Control header won't be set, maxAge property is ignored if present.

**Comment by dougwilson** [comment]
Thanks! Approach 1 is not backwards compatible, as we currently accept, without error, negative numbers and just treat it like 0.

The other two looks like you didn't see the requirement:

> a good API that does not have options that exclude one another.

**Comment by dougwilson** [comment]
We could do approach 3, without the backwards compatibility part, in the next major, which should come out dome time this year. Or maybe just in the next major have maxAge accept null which does not output the header?

**Comment by hacksparrow** [comment]
@dougwilson what does "one another" refer to in your statement "a good API that does not have options that exclude one another"?

We are used to using `false` for instructing "don't use", `null` will feel odd and inconsistent.

How about modifying approach 3 to this:

* Cache-Control is disabled by default
* It is turned on by setting the desired value to the `cacheControl` property in the options object.

?

**Comment by dougwilson** [comment]
Hi @hacksparrow, it means you don't have an API where you have `{ option1: true, option2: 'my value can be literally anything since it is ignored when option1 is true' }`.

The `Cache-Control` didn't used to exist a long time ago in Express. It was added because it is absolutely terrible practice not to have it, and it's what makes this module more feature rich than simply using native Node.js APIs to serve your files up. This was added from dozens of requests, and one since request in over 3 years won't just make the default go away like that. Maybe if there are dozens of people clamoring to make it go away, just like there were to get it added, I would reconsider, but that is not the case here.

Either having this header by default is not hurting anyone, people just deal with it, or worse: it is genuinely useful to have & people love it and one person is about to bring this crashing down back to the era of issues.

**Comment by SVasilev** [comment]
So, in conclusion should I start implementing approach 3 without the backwards compatibility part?

**Comment by hacksparrow** [comment]
@SVasilev at this stage, it will be difficult to make changes to the API. You could continue using `on-headers`.

**Comment by dougwilson** [comment]
For the time being, we'll simply be adding a `cacheControl` option that is a Boolean you can set to `false` to not send this header. The `maxAge` option will be ignored until we implement a better API and deprecate that option.
