### ISSUE TITLE
Add support for GreenKeeper

### ISSUE THREAD

**Issue by piranna** [pillarjs/send#121]
[GreenKeeper](https://greenkeeper.io/) checks automatically for newer versions of the dependencies of the projects and exec tests to know if there are some breaking changes, and it's a tool already promoted by npm team itself. `send` have a lot of fast-moving dependencies, so it would be good to use it to keep up to date.

**Comment by dougwilson** [comment]
Thanks for the suggestion, but Greenkeeper is hostile to the Node.js users by doing things like making PRs to drop support for anything below Node.js 4. Every module here supports down to Node.js 0.8 because people use them and it is not hard to support.

I use a dashboard that shows me all outdated modules across all repos I have access to and evaluate which upgrades are worth doing at the time.

**Comment by piranna** [comment]
Node.js 0.12 will end its life cycle in just a month and get unmaintained, does it truly matter to support anything older than Node.js 4?

By the way, where do you have the dashboard? I would be interested on having something similar for mine ones :-)

**Comment by dougwilson** [comment]
Just because Node.js Foundation doesn't support it doesn't somehow get people to stop using it. Many people have no influence over the version of Node.js installed on servers, others are stuck using versions locked into Linux vendor releases, and still others actually maintain internal forks of Node.js they keep up to date for shipped embedded systems. Those users would simply stop using the latest version of this module, and if there is no compelling reason we can't support old Node.js versions, module authors are doing them a disservice.

They are local scripts... I'll see about pushing a public repo to my GitHub account and ping to where it is so you can take a look :) I use it extensively to do release planning across many orgs and yo coordinate module releases for Express.

**Comment by piranna** [comment]
> They are local scripts... I'll see about pushing a public repo to my GitHub account and ping to where it is so you can take a look :) I use it extensively to do release planning across many orgs and yo coordinate module releases for Express.

That would be good! :-) Maybe you could publish them as is so we can review it?
