### ISSUE TITLE
Send divides given maxAge 

### ISSUE THREAD

**Issue by ivancsicsmarkus** [pillarjs/send#141]
https://github.com/pillarjs/send/blob/bad2a468e4ff38c13ffb5a113ce74ba9a812f804/index.js#L879

So if I say "cache it for one day!" (86400000ms) then it will only cache it for 86.4 seconds (86400ms).

**Comment by dougwilson** [comment]
Hi @ivancsicsmarkus that's right, it's divided by 1000 because the `Cache-Control` `max-age` directive is in seconds, while the value we take is in milliseconds.

You can find the specification for the `max-age` directive in `Cache-Control` in RFC 7234 sec 5.2.2.8 (https://tools.ietf.org/html/rfc7234#section-5.2.2.8):

>    Argument syntax:
>
>      delta-seconds (see Section 1.2.1)
>
>   The "max-age" response directive indicates that the response is to be
>   considered stale after its age is greater than the specified number
>   of seconds.
>
>   This directive uses the token form of the argument syntax: e.g.,
>   'max-age=5' not 'max-age="5"'.  A sender SHOULD NOT generate the
>   quoted-string form.

I hope this helps!
