### ISSUE TITLE
Filenames with periods/dots using extensions option

### ISSUE THREAD

**Issue by js-choi** [pillarjs/send#166]
Currently, the `extensions` option “is skipped if the requested file already has an extension” ([readme](https://github.com/pillarjs/send/blob/master/README.md)).

I’d like to request adding a boolean option such as `alwaysCheckExtensions`, by default `false`, such that the `extensions` is *never* skipped, even if the requested filename contains periods/dots. 

There are many cases where a filename may contain multiple dots, of which only the last would delimit the file extension. For instance, I want to use hyphens to separate most words in my HTML documents’ filenames, but I also want to delimit the different versions of the same HTML document using periods, such as `understanding-cats.en-us.html` and `understanding-cats.en-uk.html`. I would want to be able to serve these files as `understanding-cats.en-us` and `understanding-cats.en-uk`. People do similar things with differently sized versions of the same image (`icon-256px` versus `icon-1028px`) or for original versus minified versions of the same script (`jquery` versus `jquery.min`).

I ran into this problem using [express.static / serve-static](https://expressjs.com/en/resources/middleware/serve-static.html), which depends on and delegates its options to this library.

**Comment by dougwilson** [comment]
The extensions options is only designed to server extension-less URLs. Your example URLs do have extensions (the lang code), which is why it doesn't work for your use-case.

Based on your use-case description I wouldn't even use the extensions option at all. Remember it would require an extra fs stats ca for every single request if you do that, and stat calls use the Node.js thread pool so you can quickly bottleneck your app with excessive thread pool work.

If all the files have .html extension, just add the extension in the string you pass to `send` and it will serve the file in a single stat :+1: .
