### ISSUE TITLE
strong etag support?

### ISSUE THREAD

**Issue by cxn-astracz** [pillarjs/send#176]
A recent change in the behaviour of `npm pack` in npm/npm#20439 results in the same file modification time for all files packaged by npm in every build, [1985 Oct 26](https://github.com/npm/npm/blob/7302686bcc5798ed73f8d26883d65f63a85acfe7/lib/pack.js#L125). This translates to subtle caching bugs on files that aren't typically repackaged during a build, like anything from threejs, d3, angular 1 libraries, etc... I've actually spent a good day on this issue before realizing the problem, and at least on my project there appears to be no good way out.

The default configuration of express's static middleware is to send both `last-modified` and `etag` headers for caching/conditional get support, through options provided to `send`. Because of this npm change, I need to turn off last modified as it's not effective enough. Etag in general could still be useful, but the weak etag created in `send` consists of the [last modification time and the filesize](https://github.com/jshttp/etag/blob/master/index.js#L126), so in case an update results in the same bytesize for the file, etag caching isn't effective as well. That's where the subtle bugs are introduced.

After this long introduction, I'm wondering how to get out of this issue. In no particular order, this is what I have:

1. request reconsideration of strong etag support in `send` :)
2. request an updated weak etag support in `etag`, e.g. Math.max(mtime, ctime, birthtime) (because npm doesn't seem to change the other two times), probably worth a separate issue in the etag project
3. add a postinstall script that runs `find . -type f exec touch {} +` to force an effective and good mtime
4. change the build script and repackage all files and make sure a version is added to filenames or something that entirely avoids the cache

The benefit of (2) could be that only a single change is needed to address the subtle bugs appearing in a large amount of weekly downloads.

Any suggestions welcome!

**Comment by ieugen** [comment]
We are also affected by this. It caught us by surprise.

**Comment by r0mflip** [comment]
+1 for (2)

**Comment by dougwilson** [comment]
I would prefer this module does not diverge from the methodology that Apache, NGINX, etc. use for interoperability. Especially because Node.js should always be the last resort to use to server static files from the file system do the Node.js not having async file IO, and thus your thread pool will be full of file requests.

Is the same issue present when using other file serving methods like NGINX? Does npm believe this is a bug or a functions as designed?

**Comment by dougwilson** [comment]
I'm going to close this issue as stale, mainly because I never got a response to my question.

I looked it up and Apache / NGINX would have the same "problem" -- they both calculate ETags by default the same way as this module: the mtime + size. But just like Apache / NGINX, you can change the ETags in this module if you want to use a different method. For example, you could include the inode of the file, though be aware that if you use multiple servers, the ETags will differ between servers when that is done, which may cause other issues.

I'll suggest that if you are serving files that are unpacked from these npm tarballs, to do one of the above methods, or if anyone knows how to actually calculate a strong ETag without reading the entire file from disk multiple times or holding the entire file in memory, you're welcome to make a pull request to implement strong ETags.
