### ISSUE TITLE
Any plans to update mime?

### ISSUE THREAD

**Issue by SgSridhar** [pillarjs/send#188]
I have checked few issues here and just wanted to ensure the following. Please review

1. Are there any plans to update mime? 
2. I have noticed that this project depends on mime 1.x's API which is still being maintained.

The answers to the above question is year or more older, so I am looking for confirmation. Are the answers to the above questions still valid? Thanks for your time.

**Comment by dougwilson** [comment]
Hi @SgSridhar the specific plan is that we'll drop `mime` and use `mime-types` module when 1.x line needs to come out. Currently there isn't an issue with the `mime` 1.x line, so there hasn't been a big rush, especially since the last few times it needed updating it was releases in parallel with the 2.x series of `mime`.

I hope that answers your questions!
