### ISSUE TITLE
`mime` package is deprecated

### ISSUE THREAD

**Issue by evilebottnawi** [pillarjs/send#189]
https://github.com/broofa/node-mime

Will be great to migrate on other solution.

**Comment by dougwilson** [comment]
Yes, there us already a migration planned for the 1.0 release of send. Currently mime works fine as it is, even though it was archived recently. If you have further concerns than just that it is archived, we can always act sooner, otherwise we will swap it out as part of the 1.0 effort underway soon.

**Comment by dougwilson** [comment]
I've also been unsure if it is truly deprecated or not. The repo is archived, but the readme does not seem related, so to me it makes me question if it was on accident or not, as I haven't seen anything outside of that so far, but if you have additional information that would be great!

**Comment by evilebottnawi** [comment]
> Yes, there us already a migration planned for the 1.0 release of send.

Great, It's enough :smile:
