### ISSUE TITLE
Update mime dependency to 3.0

### ISSUE THREAD

**Issue by pravi** [pillarjs/send#216]
There is a new upstream version of mime and we'd like to use mime 3.0 in debian.

**Comment by dougwilson** [comment]
Hello, and thank you for your issue. Unfortunately `mime` 3.0 is incompatible with the current version of this module and thus needs to be incorporated into a new major version of this module. This is already in progress and version 1.0.0-beta.1 is published as the first preview of this work.

So I'm closing this issue as completed since the work has been done already 👍
