### ISSUE TITLE
Allow strong ETags

### ISSUE THREAD

**Issue by EvanHahn** [pillarjs/send#45]
Happy to submit a PR for this if you'd like!

**Comment by dougwilson** [comment]
Hi @marco2216 you certainly can do that! Then you can add a `headers` event listener on your `send` and look up that pre-calculated ETag and set it as the ETag header and `send` will use that instead of calculating one. You can then either leave `etag: true` if you want fallback for when you didn't set the ETag header, or `etag: false` for no fallback.

**Comment by marco2216** [comment]
Oh right, that's pretty much what I'm doing with serve-static. I was thinking if it should be a built in option in that library - I spent a good amount of time debugging why our static files changed ETag in-between deploys even though the file was identical. But that may also just be because of my inexperience with nginx etc., I read some of your answers in other threads that it's consistent with those servers to return a value based on the modified time and file length.
Or maybe, if you think that's outside the scope of serve-static, it might make sense to add a line to the readme explaining what the etag is based upon by default - I wouldn't mind doing that.

**Comment by marco2216** [comment]
Oh right, that's pretty much what I'm doing with serve-static. I was thinking if it should be a built in option in that library - I spent a good amount of time debugging why our static files changed ETag in-between deploys even though the file was identical. But that may also just be because of my inexperience with nginx etc., I read some of your answers in other threads that it's consistent with those servers to return a value based on the file-created-time and file length.
Or maybe, if you think that's outside the scope of serve-static, it might make sense to add a line to the readme explaining what the etag is based upon by default - I wouldn't mind doing that.
