### ISSUE TITLE
Extra slashes ignored

### ISSUE THREAD

**Issue by KyleJune** [pillarjs/send#79]
I noticed that if you use multiple slashes in the url, it's treated as if there is only 1 slash. This happens because there is no check for extra slashes before the path is normalized. Shouldn't it either result in a 404 error or fix the slashes with a redirect? To demonstrate this I put a list of urls that all serve the same files below.

http://expressjs.com/starter/faq.html
http://expressjs.com//starter/faq.html
http://expressjs.com/starter//faq.html
http://expressjs.com//starter//faq.html
http://expressjs.com///////////////////////////////starter/////////////////////////////////////////////faq.html

**Comment by dougwilson** [comment]
It is by design. You'll notice your file system does the same thing, so having multiple slashes wouldn't result in a 404, as the file system would still find the file anyway.

Funny enough, expressjs.com does not even run on Node.js or this library, so really, those examples demonstrate we are doing the standard thing.
