### ISSUE TITLE
don't ignore .well-known by default

### ISSUE THREAD

**Issue by coolaj86** [pillarjs/send#90]
Copied from https://github.com/expressjs/serve-static/issues/54

Unfortunately the RFC IETF or whoever decided it was a good idea to standardize on a directory that is, by default, hidden. Right?

So when I'm tearing my hair out wondering why my Let's Encrypt certs aren't getting validated....

* `https://example.com/.well-known/acme-challenge/xxxxxxxxxxxxxxx`

It's the darn `.well-known` givin' me all the troubles.

I'd like to suggest that `.well-known` (and any other RFC / IETF spec'd dirs) not be ignored by default.

Perhaps the default should be the array `['.well-known']` and you can override that value with `true`, `false`, or `[]` (ignore)?

**Comment by dougwilson** [comment]
I'm not sure why you think there is a bug in this module. By default, we do allow that to work, unless you change it to do otherwise. You can even see it working just fine using the simple example at https://github.com/pillarjs/send#small-example and serving up the file in a directory called `.well-known` (I added `root` option to make it make more sense; I should do that to the example as well):
```
$ npm i send
send@0.13.0 node_modules\send
├── destroy@1.0.3
├── escape-html@1.0.2
├── range-parser@1.0.3
├── fresh@0.3.0
├── etag@1.7.0
├── statuses@1.2.1
├── ms@0.7.1
├── debug@2.2.0
├── mime@1.3.4
├── depd@1.0.1
├── http-errors@1.3.1 (inherits@2.0.1)
└── on-finished@2.3.0 (ee-first@1.1.1)

$ cat app.js
// This is the example from the README
var http = require('http');
var send = require('send');

var app = http.createServer(function(req, res){
  send(req, req.url, { root: __dirname + '/public' }).pipe(res);
}).listen(3000);

$ mkdir public

$ mkdir public/.well-known

$ mkdir public/.well-known/acme-challenge

$ echo 'hello!' > public/.well-known/acme-challenge/xxxxxxxxxxxxxxx

$ node app &
[1] 9356

$ curl http://127.0.0.1:4000/.well-known/acme-challenge/xxxxxxxxxxxxxxx
hello!
```
If you still think there is an issue, please build upon the reproduction steps I have above and paste the way to reproduce here so I can try it out :)
