### ISSUE TITLE
Time for v1.0.0?

### ISSUE THREAD

**Issue by coolaj86** [pillarjs/send#93]
This is stable code that is widely used in production which has been carefully preserved to not break backwards compat.

Doesn't it deserve the honor of a v1.0?

**Comment by dougwilson** [comment]
Not yet. We have a huge API rewrite for this module in progress we are putting as the 1.0.0. You can see some of that rewrite in the current `1.x` branch in this repository, if you are interested :) https://github.com/pillarjs/send/tree/1.x

Because Express depends on this module, and with limited resources to do work (literally just me, completely unpaid and completely on my own spare time), I really don't have the time to maintain two lineages of this module (0.x for Express <= 4 and 1.x for Express >= 5), so the 1.0 rewrite is waiting to be released in conjunction with Express 5. This was actually what brought up the issue https://github.com/strongloop/express/issues/2449

I'm closing your issue, not because it doesn't have merit of a question, but because the only real "resolution" would be releasing 1.0 and there are different npm ranking systems that will penalize modules with issues opened for a long time :)
